In [1]:
import sklearn
sklearn.__version__

'0.23.2'

In [3]:
import numpy  as np
import pandas as pd
from sklearn.datasets import load_iris

In [4]:
iris = load_iris() 

In [6]:
type(iris)

sklearn.utils.Bunch

In [8]:
keys = iris.keys()
keys

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [15]:
# iris.data
# iris.target
# iris.target_names
# iris.feature_names
# iris.DESCR

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ============== ==== =


- 피쳐 데이터세트 확인

In [17]:
iris_data = iris.data
iris_data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

- 레이블(결정값, 타켓, 클래스) 확인

In [18]:
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

- 데이터 프레임 변환


In [20]:
iris_df = pd.DataFrame(data    = iris_data , 
                       columns = iris.feature_names)
iris_df['target'] = iris_label
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

- 학습데이터(traing data - validation data)와 테스트데이터(test data) 세트로 분리
- train_test_split(test_size , train_size , shuffle , random_state)

In [43]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(iris_data , iris_label , 
                                                       test_size=0.3 ,
                                                       shuffle = False , 
                                                       random_state = 20 )
print('train data   : \n' ,  X_train)
print('train label  : \n' , y_train)
print('test  data   : \n' , X_test)
print('test  label  : \n' , y_test)


train data   : 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 

- 알고리즘을 활용한 학습과 분류

In [44]:
from sklearn.tree import DecisionTreeClassifier

dt_clf = DecisionTreeClassifier(random_state = 20)

# 학습(fit)
dt_clf.fit(X_train , y_train) 

DecisionTreeClassifier(random_state=20)

- 예측은 학습데이터가 아닌 다른데이터(test data)를 이용하여야 한다

In [45]:
prediction = dt_clf.predict(X_test)
print('predict\n' , prediction)
print('y_test\n'  , y_test)

predict
 [2 1 2 2 2 2 2 2 2 2 2 2 2 2 1 2 1 2 1 2 2 1 1 2 1 2 2 2 1 1 2 2 2 1 2 2 2
 2 2 2 2 2 2 2 2]
y_test
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2]


- 예측 정확도 평가

In [46]:
from sklearn.metrics import accuracy_score
print('예측 정확도 : {0:.2f}'.format( accuracy_score(y_test , prediction ))) 

예측 정확도 : 0.78


In [ ]:
import numpy  as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

bad_iris = load_iris() 

train_data  = bad_iris.data
train_label = bad_iris.target

bad_dt_clf = DecisionTreeClassifier(random_state = 20)
bad_dt_clf.fit(train_data , train_label)

pred = bad_dt_clf.predict(train_data)
print('예측 정확도 : ' , accuracy_score(train_label , pred))

#### 교차검증(Cross Validation)

- KFold 방식

In [47]:
import numpy  as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.model_selection import KFold

In [50]:
fold_iris = load_iris()
fold_iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [51]:
features = fold_iris.data
label    = fold_iris.target

fold_df_clf = DecisionTreeClassifier()
fold_df_clf

DecisionTreeClassifier()

In [61]:
# 5개의 폴터 세트를 분리하여 각 폴드 세트별 정확도를 담을 리스트 생성
cv_accuracy = []
kfold = KFold(n_splits = 6)


In [63]:
n_iter = 0 
for train_idx , test_idx in kfold.split(features) :
    # print(train_idx , test_idx )
    X_train , X_val = features[train_idx] , features[test_idx]
    y_train , y_val = label[train_idx]    , label[test_idx]
    
    # 학습 및 예측
    fold_df_clf.fit(X_train , y_train)
    pred = fold_df_clf.predict(X_val)
    n_iter += 1 
    
    # 검증정확도 측정
    acc = np.round( accuracy_score(y_val , pred) , 4 )
    print('{} 교차 검증 정확도 : {} , 학습 데이터 크기 : {} , 검증 데이터 크기 : {}'
          .format(n_iter, acc , X_train.shape[0] , X_val.shape[0]))
    print('{} 검증 세트 인덱스 : {}'.format(n_iter , X_val.shape[0]))
    
    cv_accuracy.append(acc)


print('평균 검증 정확도 : {} ' , np.mean(cv_accuracy)) 


1 교차 검증 정확도 : 1.0 , 학습 데이터 크기 : 125 , 검증 데이터 크기 : 25
1 검증 세트 인덱스 : 25
2 교차 검증 정확도 : 1.0 , 학습 데이터 크기 : 125 , 검증 데이터 크기 : 25
2 검증 세트 인덱스 : 25
3 교차 검증 정확도 : 0.92 , 학습 데이터 크기 : 125 , 검증 데이터 크기 : 25
3 검증 세트 인덱스 : 25
4 교차 검증 정확도 : 0.88 , 학습 데이터 크기 : 125 , 검증 데이터 크기 : 25
4 검증 세트 인덱스 : 25
5 교차 검증 정확도 : 0.92 , 학습 데이터 크기 : 125 , 검증 데이터 크기 : 25
5 검증 세트 인덱스 : 25
6 교차 검증 정확도 : 0.88 , 학습 데이터 크기 : 125 , 검증 데이터 크기 : 25
6 검증 세트 인덱스 : 25
평균 검증 정확도 : {}  0.9333333333333332


In [62]:
for train_idx , test_idx in kfold.split(features) :
    print(train_idx , test_idx )


[ 25  26  27  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42
  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60
  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114
 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132
 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  50  51  52  53  54  55  56  57  58  59  60
  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78
  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114
 115 116 117 118 119 120 121 122 123 124 125 126 

- Stratified KFold : 불균형한 분포를 가진 데이터 집합에 적용하는 CV
- 기존 KFold 는 레이블값의 분포를 반영하지 않기 때문에 상황에 따라서 예측정확도가 0

In [67]:
fold_iris_df = pd.DataFrame(data    = fold_iris.data , 
                            columns = fold_iris.feature_names)
fold_iris_df['target'] = fold_iris.target
fold_iris_df['target'].value_counts()

2    50
1    50
0    50
Name: target, dtype: int64

In [76]:
# 문제점 확인
kfold = KFold(n_splits=3) 
n_iter = 0 
for train_idx , test_idx in kfold.split(fold_iris_df) :
    label_train = fold_iris_df['target'].iloc[train_idx]
    label_val   = fold_iris_df['target'].iloc[test_idx]
    n_iter += 1 
    print('교차 검증 {}', n_iter)
    print('학습 레이블 데이터 분포\n' , label_train.value_counts() )
    print('검증 레이블 데이터 분포' , label_val.value_counts() )

    print()

교차 검증 {} 1
학습 레이블 데이터 분포
 2    50
1    50
Name: target, dtype: int64
검증 레이블 데이터 분포 0    50
Name: target, dtype: int64

교차 검증 {} 2
학습 레이블 데이터 분포
 2    50
0    50
Name: target, dtype: int64
검증 레이블 데이터 분포 1    50
Name: target, dtype: int64

교차 검증 {} 3
학습 레이블 데이터 분포
 1    50
0    50
Name: target, dtype: int64
검증 레이블 데이터 분포 2    50
Name: target, dtype: int64



In [81]:
# 문제점 해결하기 위한 방법
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits = 3)
n_iter = 0 

for train_idx , test_idx in skf.split(fold_iris_df , fold_iris_df['target']) :
    n_iter += 1 
    
    label_train = fold_iris_df['target'].iloc[train_idx]
    label_val   = fold_iris_df['target'].iloc[test_idx]
    
    print('교차 검증 {}', n_iter)
    print('학습 레이블 데이터 분포\n' , label_train.value_counts() )
    print('검증 레이블 데이터 분포\n' , label_val.value_counts() )

    print()

교차 검증 {} 1
학습 레이블 데이터 분포
 2    34
1    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포
 1    17
0    17
2    16
Name: target, dtype: int64

교차 검증 {} 2
학습 레이블 데이터 분포
 1    34
2    33
0    33
Name: target, dtype: int64
검증 레이블 데이터 분포
 2    17
0    17
1    16
Name: target, dtype: int64

교차 검증 {} 3
학습 레이블 데이터 분포
 0    34
2    33
1    33
Name: target, dtype: int64
검증 레이블 데이터 분포
 2    17
1    17
0    16
Name: target, dtype: int64



In [88]:
# 교차검증 정확도를 확인

from sklearn.model_selection import StratifiedKFold

dt_clf = DecisionTreeClassifier( random_state = 100 ) 

skf = StratifiedKFold(n_splits = 3)
n_iter = 0 
cv_accuracy = []

for train_idx , test_idx in skf.split(features , label) :
    X_train , X_val = features[train_idx] , features[test_idx]
    y_train , y_val = label[train_idx]    , label[test_idx]
    
    # 학습 , 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_val)
    
    # 반복시 정확도 측정
    n_iter += 1
    acc = np.round( accuracy_score(y_val , pred) , 4 )
    print('{} 교차 검증 정확도 : {} , 학습 데이터 크기 : {} , 검증 데이터 크기 : {}'
          .format(n_iter, acc , X_train.shape[0] , X_val.shape[0]))
    print('{} 검증 세트 인덱스 : {}'.format(n_iter , X_val.shape[0]))
    
    cv_accuracy.append(acc)

print()
print('교차 검증 정확도 ' , np.round(cv_accuracy , 4) )
print('평균 검증 정확도 ' , np.mean(cv_accuracy ) ) 

1 교차 검증 정확도 : 0.98 , 학습 데이터 크기 : 100 , 검증 데이터 크기 : 50
1 검증 세트 인덱스 : 50
2 교차 검증 정확도 : 0.92 , 학습 데이터 크기 : 100 , 검증 데이터 크기 : 50
2 검증 세트 인덱스 : 50
3 교차 검증 정확도 : 0.96 , 학습 데이터 크기 : 100 , 검증 데이터 크기 : 50
3 검증 세트 인덱스 : 50

교차 검증 정확도  [0.98 0.92 0.96]
평균 검증 정확도  0.9533333333333333


In [85]:
fold_iris.keys

<function Bunch.keys>